spring:
  application:
    name: Hyperspace

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/Hyperspace
    username: postgres
    password: yu3506058341

  redis:
    host: 47.121.188.252
    port: 6379
    password: miniblogredis

server:
  port: 8080

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tCvmabLdf2xQcN363tz
    accessKeySecret: o2Q5xjQ7hcizJv5w2OMLlrohP4LdWZ
    bucketName: lihuahua-hyperspace

knife4j:
  enable: true

jwt:
  secret: GENERATE_SECURE_KEY
  expiration: 3600
  long-expiration: 604800
