spring:
  application:
    name: Hyperspace

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.41.43:3306/hyperspace
    username: hyperspace
    password: KFaRMeZJfrWpEA3i

  redis:
    host: localhost
    port: 6379
    password: 654321
    database: 1

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

server:
  port: 8080

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tCvmabLdf2xQcN363tz
    accessKeySecret: o2Q5xjQ7hcizJv5w2OMLlrohP4LdWZ
    bucketName: fourandone-hyperspace

knife4j:
  enable: true

jwt:
  secret: "Hyp3rsp4c3_S3cr3t_K3y_F0r_JWT_T0k3n_Signing_With_HS512_Algorithm"
  #secret: "GENERATE_SECURE_KEY"
  expiration: 43200
  long-expiration: 43200

file:
  upload:
    path: uploads
    mode: oss