-- 帖子主表
CREATE TABLE `post` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库内部自增主键',
  `post_id` varchar(64) NOT NULL COMMENT '帖子全局唯一ID（业务主键，如：post_${UUID}）',
  `user_id` varchar(64) NOT NULL COMMENT '发布者用户ID（关联user.user_id）',
  `username` varchar(100) NOT NULL COMMENT '发布者用户名（冗余存储，优化展示性能）',
  `avatar_url` varchar(255) DEFAULT NULL COMMENT '发布者头像URL（冗余存储，优化展示性能）',
  `type` varchar(20) NOT NULL COMMENT '帖子类型（video-视频、image-图文、article-文章攻略等）',
  `title` varchar(255) NOT NULL COMMENT '帖子标题',
  `content` text COMMENT '帖子内容（文字内容）',
  `cover_url` varchar(255) DEFAULT NULL COMMENT '封面图片URL',
  `video_url` varchar(255) DEFAULT NULL COMMENT '视频URL（仅对视频类型有效）',
  `duration` int DEFAULT NULL COMMENT '视频时长（秒，仅对视频类型有效）',
  `view_count` int DEFAULT '0' COMMENT '浏览次数',
  `like_count` int DEFAULT '0' COMMENT '点赞数',
  `comment_count` int DEFAULT '0' COMMENT '评论数',
  `share_count` int DEFAULT '0' COMMENT '分享数',
  `status` varchar(20) NOT NULL DEFAULT 'published' COMMENT '帖子状态（published-已发布、draft-草稿、deleted-已删除）',
  `tags` varchar(255) DEFAULT NULL COMMENT '标签（JSON数组格式）',
  `category` varchar(50) DEFAULT NULL COMMENT '分类（如：游戏攻略、生活分享等）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_post_id` (`post_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_type` (`type`),
  KEY `idx_category` (`category`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='帖子主表';